piedweb_cms_conversation:
  path: /conversation/{type}/{referring}
  controller: PiedWeb\ConversationBundle\Controller\ConversationFormController::show
  methods: [POST]
  defaults:
    step: 1
    id: 0
  requirements:
    type: '[a-zA-Z0-9-]*'
    referring: '[a-zA-Z0-9\-/]*'
    id: '[0-9]*'
    step: '[0-9]*'
