services:
  # --------
  # ContactBundle
  # --------

  PiedWeb\ConversationBundle\PiedWebConversationBundle: ~

  PiedWeb\ConversationBundle\:
    autowire: true
    resource: '../../../src/*'
    exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  PiedWeb\ConversationBundle\Controller\:
    autowire: true
    resource: '../../../src/Controller'
    tags: ['controller.service_arguments']

  piedweb.admin.conversation:
    class: PiedWeb\ConversationBundle\Admin\ConversationAdmin
    arguments:
      - ~
      - '%pwc.conversation.entity_message%'
      - ~
    tags:
      - {
          name: sonata.admin,
          manager_type: orm,
          label: admin.label.conversation,
        }
    public: true

  piedweb.conversation.notifier:
    class: PiedWeb\ConversationBundle\Service\NewMessageMailNotifier
    arguments:
      [
        '%pwc.conversation.entity_message%',
        '@mailer',
        '%pwc.email_sender%',
        '%pwc.conversation.notification_emailTo%',
        '%pwc.name%',
        '%kernel.root_dir%',
        '%pwc.conversation.notification_interval%',
        '@doctrine.orm.entity_manager',
        '@translator',
      ]

  piedweb.conversation.notification_command:
    arguments:
      - '@piedweb.conversation.notifier'
    class: PiedWeb\ConversationBundle\Command\NotificationCommand
    tags: ['console.command']

  piedweb.conversation.twig_extension:
    class: PiedWeb\ConversationBundle\Twig\AppExtension
    tags:
      - 'twig.extension'
      #- { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    arguments:
      ['@doctrine.orm.entity_manager', '%pwc.conversation.entity_message%']

  PiedWeb\ConversationBundle\Repository\MessageRepository:
    arguments: ['@doctrine', '%pwc.conversation.entity_message%']
    tags:
      - { name: doctrine.repository_service }
